/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticateImport } from './routes/authenticate'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AuthLayoutProjectsIndexImport } from './routes/_auth/_layout/projects/index'
import { Route as AuthLayoutNnsIndexImport } from './routes/_auth/_layout/nns/index'
import { Route as AuthLayoutProjectsCreateImport } from './routes/_auth/_layout/projects/create'
import { Route as AuthLayoutProjectsProjectIdIndexImport } from './routes/_auth/_layout/projects/$projectId/index'
import { Route as AuthLayoutProjectsProjectIdCreateImport } from './routes/_auth/_layout/projects/$projectId/create'

// Create/Update Routes

const AuthenticateRoute = AuthenticateImport.update({
  path: '/authenticate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutProjectsIndexRoute = AuthLayoutProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutNnsIndexRoute = AuthLayoutNnsIndexImport.update({
  path: '/nns/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutProjectsCreateRoute = AuthLayoutProjectsCreateImport.update({
  path: '/projects/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutProjectsProjectIdIndexRoute =
  AuthLayoutProjectsProjectIdIndexImport.update({
    path: '/projects/$projectId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdCreateRoute =
  AuthLayoutProjectsProjectIdCreateImport.update({
    path: '/projects/$projectId/create',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout/projects/create': {
      id: '/_auth/_layout/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthLayoutProjectsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/nns/': {
      id: '/_auth/_layout/nns/'
      path: '/nns'
      fullPath: '/nns'
      preLoaderRoute: typeof AuthLayoutNnsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/': {
      id: '/_auth/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthLayoutProjectsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/create': {
      id: '/_auth/_layout/projects/$projectId/create'
      path: '/projects/$projectId/create'
      fullPath: '/projects/$projectId/create'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/': {
      id: '/_auth/_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdIndexImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticateRoute,
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutProjectsCreateRoute,
    AuthLayoutNnsIndexRoute,
    AuthLayoutProjectsIndexRoute,
    AuthLayoutProjectsProjectIdCreateRoute,
    AuthLayoutProjectsProjectIdIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authenticate",
        "/_auth/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authenticate": {
      "filePath": "authenticate.tsx"
    },
    "/_auth/_layout": {
      "filePath": "_auth/_layout.tsx",
      "children": [
        "/_auth/_layout/projects/create",
        "/_auth/_layout/nns/",
        "/_auth/_layout/projects/",
        "/_auth/_layout/projects/$projectId/create",
        "/_auth/_layout/projects/$projectId/"
      ]
    },
    "/_auth/_layout/projects/create": {
      "filePath": "_auth/_layout/projects/create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/nns/": {
      "filePath": "_auth/_layout/nns/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/": {
      "filePath": "_auth/_layout/projects/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/create": {
      "filePath": "_auth/_layout/projects/$projectId/create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/": {
      "filePath": "_auth/_layout/projects/$projectId/index.tsx",
      "parent": "/_auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
