/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticateImport } from './routes/authenticate'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AuthLayoutProjectsIndexImport } from './routes/_auth/_layout/projects/index'
import { Route as AuthLayoutNnsIndexImport } from './routes/_auth/_layout/nns/index'
import { Route as AuthLayoutProjectsCreateImport } from './routes/_auth/_layout/projects/create'
import { Route as AuthLayoutProjectsProjectIdIndexImport } from './routes/_auth/_layout/projects/$projectId/index'
import { Route as AuthLayoutProjectsProjectIdDocumentsCreateImport } from './routes/_auth/_layout/projects/$projectId/documents/create'
import { Route as AuthLayoutProjectsProjectIdDocumentsDocumentIdIndexImport } from './routes/_auth/_layout/projects/$projectId/documents/$documentId/index'
import { Route as AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsDiffImport } from './routes/_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff'
import { Route as AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsCreateImport } from './routes/_auth/_layout/projects/$projectId/documents/$documentId/revisions/create'
import { Route as AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsRevisionIdIndexImport } from './routes/_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/index'

// Create/Update Routes

const AuthenticateRoute = AuthenticateImport.update({
  path: '/authenticate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutProjectsIndexRoute = AuthLayoutProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutNnsIndexRoute = AuthLayoutNnsIndexImport.update({
  path: '/nns/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutProjectsCreateRoute = AuthLayoutProjectsCreateImport.update({
  path: '/projects/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutProjectsProjectIdIndexRoute =
  AuthLayoutProjectsProjectIdIndexImport.update({
    path: '/projects/$projectId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdDocumentsCreateRoute =
  AuthLayoutProjectsProjectIdDocumentsCreateImport.update({
    path: '/projects/$projectId/documents/create',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdDocumentsDocumentIdIndexRoute =
  AuthLayoutProjectsProjectIdDocumentsDocumentIdIndexImport.update({
    path: '/projects/$projectId/documents/$documentId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsDiffRoute =
  AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsDiffImport.update({
    path: '/projects/$projectId/documents/$documentId/revisions/diff',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsCreateRoute =
  AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsCreateImport.update({
    path: '/projects/$projectId/documents/$documentId/revisions/create',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsRevisionIdIndexRoute =
  AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsRevisionIdIndexImport.update(
    {
      path: '/projects/$projectId/documents/$documentId/revisions/$revisionId/',
      getParentRoute: () => AuthLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout/projects/create': {
      id: '/_auth/_layout/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthLayoutProjectsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/nns/': {
      id: '/_auth/_layout/nns/'
      path: '/nns'
      fullPath: '/nns'
      preLoaderRoute: typeof AuthLayoutNnsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/': {
      id: '/_auth/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthLayoutProjectsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/': {
      id: '/_auth/_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/documents/create': {
      id: '/_auth/_layout/projects/$projectId/documents/create'
      path: '/projects/$projectId/documents/create'
      fullPath: '/projects/$projectId/documents/create'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdDocumentsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/documents/$documentId/': {
      id: '/_auth/_layout/projects/$projectId/documents/$documentId/'
      path: '/projects/$projectId/documents/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdDocumentsDocumentIdIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/create': {
      id: '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/create'
      path: '/projects/$projectId/documents/$documentId/revisions/create'
      fullPath: '/projects/$projectId/documents/$documentId/revisions/create'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff': {
      id: '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff'
      path: '/projects/$projectId/documents/$documentId/revisions/diff'
      fullPath: '/projects/$projectId/documents/$documentId/revisions/diff'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsDiffImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/': {
      id: '/_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/'
      path: '/projects/$projectId/documents/$documentId/revisions/$revisionId'
      fullPath: '/projects/$projectId/documents/$documentId/revisions/$revisionId'
      preLoaderRoute: typeof AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsRevisionIdIndexImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticateRoute,
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutProjectsCreateRoute,
    AuthLayoutNnsIndexRoute,
    AuthLayoutProjectsIndexRoute,
    AuthLayoutProjectsProjectIdIndexRoute,
    AuthLayoutProjectsProjectIdDocumentsCreateRoute,
    AuthLayoutProjectsProjectIdDocumentsDocumentIdIndexRoute,
    AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsCreateRoute,
    AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsDiffRoute,
    AuthLayoutProjectsProjectIdDocumentsDocumentIdRevisionsRevisionIdIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authenticate",
        "/_auth/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authenticate": {
      "filePath": "authenticate.tsx"
    },
    "/_auth/_layout": {
      "filePath": "_auth/_layout.tsx",
      "children": [
        "/_auth/_layout/projects/create",
        "/_auth/_layout/nns/",
        "/_auth/_layout/projects/",
        "/_auth/_layout/projects/$projectId/",
        "/_auth/_layout/projects/$projectId/documents/create",
        "/_auth/_layout/projects/$projectId/documents/$documentId/",
        "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/create",
        "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff",
        "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/"
      ]
    },
    "/_auth/_layout/projects/create": {
      "filePath": "_auth/_layout/projects/create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/nns/": {
      "filePath": "_auth/_layout/nns/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/": {
      "filePath": "_auth/_layout/projects/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/": {
      "filePath": "_auth/_layout/projects/$projectId/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/documents/create": {
      "filePath": "_auth/_layout/projects/$projectId/documents/create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/documents/$documentId/": {
      "filePath": "_auth/_layout/projects/$projectId/documents/$documentId/index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/create": {
      "filePath": "_auth/_layout/projects/$projectId/documents/$documentId/revisions/create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff": {
      "filePath": "_auth/_layout/projects/$projectId/documents/$documentId/revisions/diff.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/": {
      "filePath": "_auth/_layout/projects/$projectId/documents/$documentId/revisions/$revisionId/index.tsx",
      "parent": "/_auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
