// This file is generated by npm run build:icons
  
  export type IconName =
	| "briefcase-outline"
	| "building-outline"
	| "buildings-outline"
	| "caret-down-outline"
	| "caret-up-down-outline"
	| "caret-up-outline"
	| "chevron-down-outline"
	| "chevron-left-outline"
	| "chevron-right-outline"
	| "chevron-up-outline"
	| "file-orientation-outline"
	| "file-outline"
	| "file-stack-outline"
	| "files-outline"
	| "git-compare-outline"
	| "infinity-outline"
	| "user-check-outline"
	| "user-outline"
	| "users-outline"
	| "x-outline";
  