// This file is generated by npm run build:icons
  
  export type IconName =
	| "briefcase-outline"
	| "building-outline"
	| "buildings-outline"
	| "file-orientation-outline"
	| "file-outline"
	| "file-stack-outline"
	| "files-outline"
	| "infinity-outline"
	| "user-outline"
	| "users-outline";
  